### ISSUE TITLE
Crear endpoint /v1/cards GET

### ISSUE THREAD

**Issue by santiruffino** [Frontend-Cafe/healthy-dev-backend#5]
Este endpoint nos va a permitir traer todas las tarjetas que existan. Para el MVP va a ser consumido por la pagina Homepage.

**Metodo:** GET
**Parametros:**
- limit = Cantidad de resultados (default 15)
- offset = ID desde el cual retorna (default ultimo o primero)

```
{
    "id": "index de la db",
    "title": "titulo de la card",
    "description": "texto descripcion",
    "photo": "url a la imagen",
    "externalUrl": "url a un sitio externo"
}
```

**Comment by santiruffino** [comment]
El endpoint tiene que retornar un json con el siguiente formato:
`{
    "id": "index de la db",
    "title": "titulo de la card",
    "description": "texto descripcion",
    "photo": "url a la imagen",
    "url": "url de la card"
}`

**Comment by franmper** [comment]
en este quedamos en que la imagen se sube desde el almacenamiento de la persona que crea la card y la logica la manejamos en el mismo endpoint, no?

**Comment by AndresRDC** [comment]
Este es el GET, pero si, en el POST de creación se carga todo, el file también.

**Comment by franmper** [comment]
ah sisi, perdón. Pense que era el POST. Si esta bien, en el post va a manejar todo.

**Comment by santiruffino** [comment]
Che, estoy viendo los diseños del Front, y me parece que este endpoint no deberia retornar tantas cosas. Al fin, se usa solo para el home, por lo que muchos parametros no van a ser consumidos en este momento. Adjunto captura de la informacion que se muestra en el HOME

![image](https://user-images.githubusercontent.com/27986940/81029269-a7b3ca00-8e5a-11ea-9f13-2fe5ca1eb183.png)

**Comment by santiruffino** [comment]
Por lo tanto, propongo que el response sea:
```
{
    "id": "index de la db",
    "title": "titulo de la card",
    "photo": "url a la imagen",
}
```

**Comment by AndresRDC** [comment]
Comúnmente ponen un  poco de descripción y como aun no estaba definido. Pero si ya no haría falta.

**Comment by santiruffino** [comment]
Claro, pero yo creo que la UI no esta pensada para la descripcion (No la nueva) jajaja. De ultima sera algo para hablar con la diseñadora y ver que onda. Pero me parece bastante limpio solo con el titulo

**Comment by AndresRDC** [comment]
No, esta perfecto así, solo aclaraba porque habíamos incluido la descripción.

**Comment by AndresRDC** [comment]
En caso de éxito retorna un array de vista previa de tarjetas (id, title, photo) en orden por id descendente para obtener los últimos creados primero. Opcionalmente se puede enviar como parámetro, además de offset (por defecto en 0) y limit (por defecto en 15), el parámetro search para poder filtrar las cards que incluyan en title o description la cadena de texto enviada.
