### ISSUE TITLE
Crear endpoint /v1/cards/:id

### ISSUE THREAD

**Issue by santiruffino** [Frontend-Cafe/healthy-dev-backend#6]
Este endpoint nos va a permitir traer informacion de UNA tarjeta existente.

Metodo: GET
Parametros:

**Comment by franmper** [comment]
Este pide id como parametro, y debería tener validación de si el id pasado es correcto.

**Comment by santiruffino** [comment]
Fran, por validar el ID te referis a validar si es un int cuando el usuario manda el dato? O validar si existe en la db?
