### ISSUE TITLE
Crear endpoint /v1/cards POST

### ISSUE THREAD

**Issue by santiruffino** [Frontend-Cafe/healthy-dev-backend#7]
Este endpoint se va a usar para crear una nueva tarjeta

Metodo: POST
Parametros a enviar:
```
{
title: string (requerido)
description: string (requerido)
photo: file? (requerido?)
externalUrl: string (opcional)
}
```

**Comment by franmper** [comment]
```
title: string (requerido)
description: string (requerido)
photo: file? (requerido?)
url: string (opcional)
```

**Comment by santiruffino** [comment]
Friendly reminder: Este endpoint incluye la funcionalidad de cargar la imagen en X plataforma

**Comment by santiruffino** [comment]
Friendly pregunta. El user que armar la card deberia venir como un parametro?

**Comment by AndresRDC** [comment]
El user se va a obtener del payload JWT, pero aun no en esta etapa. Ya hay algo hecho al respecto luego se completará y se integrará.

**Comment by AndresRDC** [comment]
Recordar que para mayor claridad url se modifico a redirection_url y es un parámetro opcional.

**Comment by santiruffino** [comment]
`redirection_url ` o `external_url`? Estoy pensando cual puede ser las preciso

**Comment by franmper** [comment]
external_url me gusto mas Santi.

**Comment by franmper** [comment]
Este endpoint POST/cards pide 4 parametros en el body (title, description, photo, externalUrl) de los cuales salvo el photo que es una imagen, la cual si no suben una imagen les va a devolver un placeholder precargado (a definir cual va a ser), el resto son strings. Solo title y description son obligatorios por el momento.
Si todo es correcto devolverá un objeto con el id de la nueva card:
` { "idOfTheNewCard": 10 }`

**Comment by santiruffino** [comment]
@franmper el ExternalUrl es un link a una plataforma de terceros, y no una imagen. Un ejemplo seria un video de youtube, o una receta de cocina de internet. No es contenido de healthy

**Comment by franmper** [comment]
Sisi Santi, está como string, en este caso le puse la misma url nomás, pero es un string.
